In [5]:
import cobra
import pandas as pd

In [2]:
recon3D = cobra.io.load_matlab_model('/Users/claudiavicentecomorera/Desktop/TFG/Data/Recon3D_301/Recon3DModel_301.mat')
recon3D

No defined compartments in model Recon3DModel. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, g, i, l, m, n, r, x

In [11]:
IDs = []
subsystems = []

for rx in recon3D.reactions:
    IDs.append(rx.id)
    subsystems.append(recon3D.get_associated_groups(rx))

subsytems_df = pd.DataFrame({'ID': IDs, 'Subsystem': subsystems})
subsytems_df

                 ID                    Subsystem
0      10FTHF5GLUtl       [Transport, lysosomal]
1      10FTHF5GLUtm   [Transport, mitochondrial]
2      10FTHF6GLUtl       [Transport, lysosomal]
3      10FTHF6GLUtm   [Transport, mitochondrial]
4      10FTHF7GLUtl       [Transport, lysosomal]
...             ...                          ...
10595    CYOR_u10mi  [Oxidative phosphorylation]
10596          Htmi   [Transport, mitochondrial]
10597   NADH2_u10mi  [Oxidative phosphorylation]
10598       CYOOm3i  [Oxidative phosphorylation]
10599       CYOOm2i  [Oxidative phosphorylation]

[10600 rows x 2 columns]

In [17]:
IDs = []
subsystems = []

for rx in recon3D.reactions:
    IDs.append(rx.id)
    subsystems.append(recon3D.get_associated_groups(rx))

subsystems_df = pd.DataFrame({'ID': IDs, 'Subsystem': subsystems})
subsystems_df = subsystems_df.explode('Subsystem').reset_index(drop = True)
subsystems_df

                 ID                  Subsystem
0      10FTHF5GLUtl       Transport, lysosomal
1      10FTHF5GLUtm   Transport, mitochondrial
2      10FTHF6GLUtl       Transport, lysosomal
3      10FTHF6GLUtm   Transport, mitochondrial
4      10FTHF7GLUtl       Transport, lysosomal
...             ...                        ...
10595    CYOR_u10mi  Oxidative phosphorylation
10596          Htmi   Transport, mitochondrial
10597   NADH2_u10mi  Oxidative phosphorylation
10598       CYOOm3i  Oxidative phosphorylation
10599       CYOOm2i  Oxidative phosphorylation

[10600 rows x 2 columns]

In [19]:
subsytems_df.to_csv('/Users/claudiavicentecomorera/Desktop/TFG/Data/Recon3D_301/recon3D_subsystems.csv')